#!/usr/bin/env python3
"""Convert the MAME 'galaga' ROM set into a C header for SWARMFIGHTER.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Graphics are decoded here with the exact MAME gfx_layout definitions so the
firmware just indexes pixels. Output arrays:
  ga_rom_cpu1[0x4000], ga_rom_cpu2[0x1000], ga_rom_cpu3[0x1000]
  ga_tiles[256][64]  (8x8, 2-bit pixel values), ga_sprites[128][256] (16x16)
  ga_prom_palette[32], ga_prom_charlut[256], ga_prom_spritelut[256], ga_prom_wave[256]
"""
import sys, zlib
from pathlib import Path

EXPECTED = {
    'gg1_1b.3p': (0x1000, 0xab036c9f), 'gg1_2b.3m': (0x1000, 0xd9232240),
    'gg1_3.2m': (0x1000, 0x753ce503),  'gg1_4b.2l': (0x1000, 0x499fcc76),
    'gg1_5b.3f': (0x1000, 0xbb5caae3), 'gg1_7b.2c': (0x1000, 0xd016686b),
    'gg1_9.4l': (0x1000, 0x58b2f47c),  'gg1_11.4d': (0x1000, 0xad447c80),
    'gg1_10.4f': (0x1000, 0xdd6f1afc),
    'prom-5.5n': (0x20, 0x54603c6b), 'prom-4.2n': (0x100, 0x59b6edab),
    'prom-3.1c': (0x100, 0x4a04bb6b), 'prom-1.1d': (0x100, 0x7a2815b4),
}

def load(romdir, name):
    data = (romdir / name).read_bytes()
    size, crc = EXPECTED[name]
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    if zlib.crc32(data) & 0xffffffff != crc:
        print(f'  warning: {name} crc32 {zlib.crc32(data):08x} != expected {crc:08x}')
    print(f'  {name}: {len(data)} bytes ok')
    return data

def decode(data, width, height, planes, xoff, yoff, inc_bits, count):
    """MAME gfx_layout decode: bit offsets, MSB first within each byte."""
    out = bytearray()
    for c in range(count):
        base = c * inc_bits
        for y in range(height):
            for x in range(width):
                v = 0
                for p, poff in enumerate(planes):
                    off = base + yoff[y] + xoff[x] + poff
                    bit = (data[off >> 3] >> (7 - (off & 7))) & 1
                    v |= bit << p
                out.append(v)
    return bytes(out)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i+16]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'galaga')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cpu1 = b''.join(load(romdir, n) for n in ('gg1_1b.3p', 'gg1_2b.3m', 'gg1_3.2m', 'gg1_4b.2l'))
    cpu2 = load(romdir, 'gg1_5b.3f')
    cpu3 = load(romdir, 'gg1_7b.2c')
    gfx1 = load(romdir, 'gg1_9.4l')
    gfx2 = load(romdir, 'gg1_11.4d') + load(romdir, 'gg1_10.4f')
    # charlayout_2bpp: planes {0,4}, x = STEP4(8*8,1), STEP4(0,1); y = STEP8(0,8); 16*8 bits per char
    tiles = decode(gfx1, 8, 8, [0, 4], [64, 65, 66, 67, 0, 1, 2, 3], [y * 8 for y in range(8)], 128, 256)
    # spritelayout_galaga: planes {0,4}, x = STEP4(0,1) STEP4(64,1) STEP4(128,1) STEP4(192,1); y = STEP8(0,8) STEP8(256,8); 64*8
    xoff = [0, 1, 2, 3, 64, 65, 66, 67, 128, 129, 130, 131, 192, 193, 194, 195]
    yoff = [y * 8 for y in range(8)] + [256 + y * 8 for y in range(8)]
    sprites = decode(gfx2, 16, 16, [0, 4], xoff, yoff, 512, 128)
    out = ['/* galaga_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef GALAGA_ROMS_H', '#define GALAGA_ROMS_H', '#include <stdint.h>', '',
           c_array('ga_rom_cpu1', cpu1, '[0x4000]'), '', c_array('ga_rom_cpu2', cpu2, '[0x1000]'), '',
           c_array('ga_rom_cpu3', cpu3, '[0x1000]'), '',
           c_array('ga_tiles', tiles, '[256 * 64]'), '', c_array('ga_sprites', sprites, '[128 * 256]'), '',
           c_array('ga_prom_palette', load(romdir, 'prom-5.5n'), '[32]'), '',
           c_array('ga_prom_charlut', load(romdir, 'prom-4.2n'), '[256]'), '',
           c_array('ga_prom_spritelut', load(romdir, 'prom-3.1c'), '[256]'), '',
           c_array('ga_prom_wave', load(romdir, 'prom-1.1d'), '[256]'), '',
           '#endif']
    (outdir / 'galaga_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "galaga_roms.h"}')

if __name__ == '__main__':
    main()
